# Generated by Django 4.1.2 on 2022-10-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_patrticipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='patrticipants',
            new_name='participants',
        ),
    ]
